HOST_IP = "localhost"
USER = "root"
PASSWORD = "Y3414071i!"
GROUP_NAME = "Group3"
DEVICE_ID = "DeviceA"

MQTT_HOSTNAME = "nam1.cloud.thethings.network"
MQTT_USERNAME = "4id3-group3-2025@ttn"
MQTT_API_KEY = "NNSXS.IIUHHZVFSLBU6GUDY3AVTKKKBQJDRE3ULC6PSDY.VRMEEHIVIGZXR3TGEWR7CKJ5KDMFGBA4JSL4ZREE6MLFXFWU6V7Q"
MQTT_PORT = 1883
MQTT_TOPIC = "#"

